name: Build Vue App

on:
  push:
    branches:
      - 'vue-frontend'     # replace with your Vue branch name

permissions:
  contents: read

env:
  DIST_DIR: 'dist'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist
          path: ${{ env.DIST_DIR }}
